// Generated by gencpp from file newmind_test/ImageAnalyzerResult.msg
// DO NOT EDIT!


#ifndef NEWMIND_TEST_MESSAGE_IMAGEANALYZERRESULT_H
#define NEWMIND_TEST_MESSAGE_IMAGEANALYZERRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace newmind_test
{
template <class ContainerAllocator>
struct ImageAnalyzerResult_
{
  typedef ImageAnalyzerResult_<ContainerAllocator> Type;

  ImageAnalyzerResult_()
    : color()  {
    }
  ImageAnalyzerResult_(const ContainerAllocator& _alloc)
    : color(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _color_type;
  _color_type color;





  typedef boost::shared_ptr< ::newmind_test::ImageAnalyzerResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::newmind_test::ImageAnalyzerResult_<ContainerAllocator> const> ConstPtr;

}; // struct ImageAnalyzerResult_

typedef ::newmind_test::ImageAnalyzerResult_<std::allocator<void> > ImageAnalyzerResult;

typedef boost::shared_ptr< ::newmind_test::ImageAnalyzerResult > ImageAnalyzerResultPtr;
typedef boost::shared_ptr< ::newmind_test::ImageAnalyzerResult const> ImageAnalyzerResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::newmind_test::ImageAnalyzerResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::newmind_test::ImageAnalyzerResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace newmind_test

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/lunar/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/lunar/share/std_msgs/cmake/../msg'], 'newmind_test': ['/home/username/catkin_workspace/devel/share/newmind_test/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::newmind_test::ImageAnalyzerResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::newmind_test::ImageAnalyzerResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::newmind_test::ImageAnalyzerResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::newmind_test::ImageAnalyzerResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::newmind_test::ImageAnalyzerResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::newmind_test::ImageAnalyzerResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::newmind_test::ImageAnalyzerResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "28a65ddb6f34603fc399ea0ac92274b8";
  }

  static const char* value(const ::newmind_test::ImageAnalyzerResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x28a65ddb6f34603fULL;
  static const uint64_t static_value2 = 0xc399ea0ac92274b8ULL;
};

template<class ContainerAllocator>
struct DataType< ::newmind_test::ImageAnalyzerResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "newmind_test/ImageAnalyzerResult";
  }

  static const char* value(const ::newmind_test::ImageAnalyzerResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::newmind_test::ImageAnalyzerResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#result\n\
float32[] color\n\
";
  }

  static const char* value(const ::newmind_test::ImageAnalyzerResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::newmind_test::ImageAnalyzerResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.color);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImageAnalyzerResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::newmind_test::ImageAnalyzerResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::newmind_test::ImageAnalyzerResult_<ContainerAllocator>& v)
  {
    s << indent << "color[]" << std::endl;
    for (size_t i = 0; i < v.color.size(); ++i)
    {
      s << indent << "  color[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.color[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NEWMIND_TEST_MESSAGE_IMAGEANALYZERRESULT_H
