// Generated by gencpp from file newmind_test/ImageAnalyzerGoal.msg
// DO NOT EDIT!


#ifndef NEWMIND_TEST_MESSAGE_IMAGEANALYZERGOAL_H
#define NEWMIND_TEST_MESSAGE_IMAGEANALYZERGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace newmind_test
{
template <class ContainerAllocator>
struct ImageAnalyzerGoal_
{
  typedef ImageAnalyzerGoal_<ContainerAllocator> Type;

  ImageAnalyzerGoal_()
    : mode(false)  {
    }
  ImageAnalyzerGoal_(const ContainerAllocator& _alloc)
    : mode(false)  {
  (void)_alloc;
    }



   typedef uint8_t _mode_type;
  _mode_type mode;





  typedef boost::shared_ptr< ::newmind_test::ImageAnalyzerGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::newmind_test::ImageAnalyzerGoal_<ContainerAllocator> const> ConstPtr;

}; // struct ImageAnalyzerGoal_

typedef ::newmind_test::ImageAnalyzerGoal_<std::allocator<void> > ImageAnalyzerGoal;

typedef boost::shared_ptr< ::newmind_test::ImageAnalyzerGoal > ImageAnalyzerGoalPtr;
typedef boost::shared_ptr< ::newmind_test::ImageAnalyzerGoal const> ImageAnalyzerGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::newmind_test::ImageAnalyzerGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::newmind_test::ImageAnalyzerGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace newmind_test

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/lunar/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/lunar/share/std_msgs/cmake/../msg'], 'newmind_test': ['/home/username/catkin_workspace/devel/share/newmind_test/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::newmind_test::ImageAnalyzerGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::newmind_test::ImageAnalyzerGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::newmind_test::ImageAnalyzerGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::newmind_test::ImageAnalyzerGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::newmind_test::ImageAnalyzerGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::newmind_test::ImageAnalyzerGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::newmind_test::ImageAnalyzerGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f3124ebba8ebedcd8ba82847d482ceb7";
  }

  static const char* value(const ::newmind_test::ImageAnalyzerGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf3124ebba8ebedcdULL;
  static const uint64_t static_value2 = 0x8ba82847d482ceb7ULL;
};

template<class ContainerAllocator>
struct DataType< ::newmind_test::ImageAnalyzerGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "newmind_test/ImageAnalyzerGoal";
  }

  static const char* value(const ::newmind_test::ImageAnalyzerGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::newmind_test::ImageAnalyzerGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal\n\
bool  mode\n\
";
  }

  static const char* value(const ::newmind_test::ImageAnalyzerGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::newmind_test::ImageAnalyzerGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImageAnalyzerGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::newmind_test::ImageAnalyzerGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::newmind_test::ImageAnalyzerGoal_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NEWMIND_TEST_MESSAGE_IMAGEANALYZERGOAL_H
