(cl:defpackage newmind_test-msg
  (:use )
  (:export
   "<IMAGEANALYZERACTION>"
   "IMAGEANALYZERACTION"
   "<IMAGEANALYZERACTIONFEEDBACK>"
   "IMAGEANALYZERACTIONFEEDBACK"
   "<IMAGEANALYZERACTIONGOAL>"
   "IMAGEANALYZERACTIONGOAL"
   "<IMAGEANALYZERACTIONRESULT>"
   "IMAGEANALYZERACTIONRESULT"
   "<IMAGEANALYZERFEEDBACK>"
   "IMAGEANALYZERFEEDBACK"
   "<IMAGEANALYZERGOAL>"
   "IMAGEANALYZERGOAL"
   "<IMAGEANALYZERRESULT>"
   "IMAGEANALYZERRESULT"
  ))

