; Auto-generated. Do not edit!


(cl:in-package newmind_test-msg)


;//! \htmlinclude ImageAnalyzerResult.msg.html

(cl:defclass <ImageAnalyzerResult> (roslisp-msg-protocol:ros-message)
  ((color
    :reader color
    :initarg :color
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0)))
)

(cl:defclass ImageAnalyzerResult (<ImageAnalyzerResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ImageAnalyzerResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ImageAnalyzerResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name newmind_test-msg:<ImageAnalyzerResult> is deprecated: use newmind_test-msg:ImageAnalyzerResult instead.")))

(cl:ensure-generic-function 'color-val :lambda-list '(m))
(cl:defmethod color-val ((m <ImageAnalyzerResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader newmind_test-msg:color-val is deprecated.  Use newmind_test-msg:color instead.")
  (color m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ImageAnalyzerResult>) ostream)
  "Serializes a message object of type '<ImageAnalyzerResult>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'color))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'color))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ImageAnalyzerResult>) istream)
  "Deserializes a message object of type '<ImageAnalyzerResult>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'color) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'color)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ImageAnalyzerResult>)))
  "Returns string type for a message object of type '<ImageAnalyzerResult>"
  "newmind_test/ImageAnalyzerResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ImageAnalyzerResult)))
  "Returns string type for a message object of type 'ImageAnalyzerResult"
  "newmind_test/ImageAnalyzerResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ImageAnalyzerResult>)))
  "Returns md5sum for a message object of type '<ImageAnalyzerResult>"
  "28a65ddb6f34603fc399ea0ac92274b8")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ImageAnalyzerResult)))
  "Returns md5sum for a message object of type 'ImageAnalyzerResult"
  "28a65ddb6f34603fc399ea0ac92274b8")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ImageAnalyzerResult>)))
  "Returns full string definition for message of type '<ImageAnalyzerResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result~%float32[] color~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ImageAnalyzerResult)))
  "Returns full string definition for message of type 'ImageAnalyzerResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result~%float32[] color~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ImageAnalyzerResult>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'color) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ImageAnalyzerResult>))
  "Converts a ROS message object to a list"
  (cl:list 'ImageAnalyzerResult
    (cl:cons ':color (color msg))
))
