; Auto-generated. Do not edit!


(cl:in-package newmind_test-msg)


;//! \htmlinclude ImageAnalyzerFeedback.msg.html

(cl:defclass <ImageAnalyzerFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass ImageAnalyzerFeedback (<ImageAnalyzerFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ImageAnalyzerFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ImageAnalyzerFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name newmind_test-msg:<ImageAnalyzerFeedback> is deprecated: use newmind_test-msg:ImageAnalyzerFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ImageAnalyzerFeedback>) ostream)
  "Serializes a message object of type '<ImageAnalyzerFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ImageAnalyzerFeedback>) istream)
  "Deserializes a message object of type '<ImageAnalyzerFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ImageAnalyzerFeedback>)))
  "Returns string type for a message object of type '<ImageAnalyzerFeedback>"
  "newmind_test/ImageAnalyzerFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ImageAnalyzerFeedback)))
  "Returns string type for a message object of type 'ImageAnalyzerFeedback"
  "newmind_test/ImageAnalyzerFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ImageAnalyzerFeedback>)))
  "Returns md5sum for a message object of type '<ImageAnalyzerFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ImageAnalyzerFeedback)))
  "Returns md5sum for a message object of type 'ImageAnalyzerFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ImageAnalyzerFeedback>)))
  "Returns full string definition for message of type '<ImageAnalyzerFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ImageAnalyzerFeedback)))
  "Returns full string definition for message of type 'ImageAnalyzerFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ImageAnalyzerFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ImageAnalyzerFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ImageAnalyzerFeedback
))
