; Auto-generated. Do not edit!


(cl:in-package newmind_test-msg)


;//! \htmlinclude ImageAnalyzerGoal.msg.html

(cl:defclass <ImageAnalyzerGoal> (roslisp-msg-protocol:ros-message)
  ((mode
    :reader mode
    :initarg :mode
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass ImageAnalyzerGoal (<ImageAnalyzerGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ImageAnalyzerGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ImageAnalyzerGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name newmind_test-msg:<ImageAnalyzerGoal> is deprecated: use newmind_test-msg:ImageAnalyzerGoal instead.")))

(cl:ensure-generic-function 'mode-val :lambda-list '(m))
(cl:defmethod mode-val ((m <ImageAnalyzerGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader newmind_test-msg:mode-val is deprecated.  Use newmind_test-msg:mode instead.")
  (mode m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ImageAnalyzerGoal>) ostream)
  "Serializes a message object of type '<ImageAnalyzerGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'mode) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ImageAnalyzerGoal>) istream)
  "Deserializes a message object of type '<ImageAnalyzerGoal>"
    (cl:setf (cl:slot-value msg 'mode) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ImageAnalyzerGoal>)))
  "Returns string type for a message object of type '<ImageAnalyzerGoal>"
  "newmind_test/ImageAnalyzerGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ImageAnalyzerGoal)))
  "Returns string type for a message object of type 'ImageAnalyzerGoal"
  "newmind_test/ImageAnalyzerGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ImageAnalyzerGoal>)))
  "Returns md5sum for a message object of type '<ImageAnalyzerGoal>"
  "f3124ebba8ebedcd8ba82847d482ceb7")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ImageAnalyzerGoal)))
  "Returns md5sum for a message object of type 'ImageAnalyzerGoal"
  "f3124ebba8ebedcd8ba82847d482ceb7")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ImageAnalyzerGoal>)))
  "Returns full string definition for message of type '<ImageAnalyzerGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%bool  mode~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ImageAnalyzerGoal)))
  "Returns full string definition for message of type 'ImageAnalyzerGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%bool  mode~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ImageAnalyzerGoal>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ImageAnalyzerGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'ImageAnalyzerGoal
    (cl:cons ':mode (mode msg))
))
